
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 430936
	#The name of the modpack
	modpackName = "99 Mods on the Wall: Forge"
	#The version of the modpack
	modpackVersion = "1.18.1-2.5.3"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

